title: Abhishek Nan # your name (or website title) here
logo: "/images/logome.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am currently pursuing my Master in Science (MSc.) degree at the University of Alberta. I specialize in Machine Learning, especially in the area of Computer Vision. I am currently looking for full-time opportunities.
  <br>
  Before my graduate studies, I worked for Microsoft as a Software Engineer in the Cloud and AI group for 3 years. I have a Bachelor of Technology in Computer Science.
  <br>
  I am interested in roles which allow me to apply my skills as a machine learning specialist, especially in computer vision but not exclusively.
  <br><br>
  <a href="https://www.linkedin.com/in/abhisheknan/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-155101846-1 # your Google Analytics tracking ID here
